source 'https://Jasperav@bitbucket.org/Jasperav/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’13.0’

use_frameworks!
target 'JVBadgeView_Tests' do
  pod 'JVBadgeView', :path => '../'
  
  
end
